---
abstract: 'base class for Dreamhack::Solitaire::Medici and (possible) for other modules (in future)'
author:
  - 'gugo <gugo@cpan.org>'
build_requires:
  Test::More: '0.98'
configure_requires:
  Module::Build::Tiny: '0.035'
dynamic_config: 0
generated_by: 'Minilla/v2.4.1, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dreamhack-Solitaire
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Dreamhack::Solitaire:
    file: lib/Dreamhack/Solitaire.pm
    version: '0.01'
requires:
  List::MoreUtils: '0.413'
  List::Util: '0'
  perl: '5.008001'
resources:
  bugtracker: https://github.com/gugo-kaluga/Dreamhack-Solitaire/issues
  homepage: https://github.com/gugo-kaluga/Dreamhack-Solitaire
  repository: git://github.com/gugo-kaluga/Dreamhack-Solitaire.git
version: '0.01'
